1-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persona [
 <!ELEMENT persona EMPTY>
 <!ATTLIST persona nombre CDATA #IMPLIED>
]>
<persona nombre="03141592E" />


2-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicula [
 <!ELEMENT pelicula EMPTY>
 <!ATTLIST pelicula titulo CDATA #IMPLIED>
]>
<pelicula titulo="La diligencia"/>


3-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cuadros [
 <!ELEMENT cuadros (cuadro*)>
 <!ELEMENT cuadro EMPTY>
 <!ATTLIST cuadro titulo ID #REQUIRED>
 <!ATTLIST cuadro autor CDATA #REQUIRED>
]>
<cuadros>
 <cuadro titulo="AdányEva" autor="Alberto Durero" />
 <cuadro autor="Lucas Cranach, el viejo" titulo="AdányEva2" />
</cuadros>


4-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaCompra [
 <!ELEMENT listaCompra (item*)>
 <!ELEMENT item EMPTY>
 <!ATTLIST item nombre CDATA #REQUIRED>
 <!ATTLIST item cantidad CDATA #REQUIRED>
]>
<listaCompra>
 <item nombre="leche" cantidad="12 litros" />
 <item nombre="pan" cantidad="3 barras de cuarto" />
</listaCompra>


5-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol [
 <!ELEMENT futbol (jugador*)>
 <!ELEMENT jugador EMPTY>
 <!ATTLIST jugador nombre NMTOKENS #REQUIRED>
 <!ATTLIST jugador codigo ID #REQUIRED>
]>
 <futbol>
<jugador nombre="Alfredo Di Stéfano" codigo="A1"/>
<jugador nombre="Edison Arantes do Nascimento Pelé" codigo="A2" />
<jugador nombre="Diego Armando Maradona" codigo="A3" />
<jugador nombre="Johan Cruyff" codigo="A4" />
</futbol>


6-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol [
 <!ELEMENT futbol ((jugador|equipo)*)>
 <!ELEMENT jugador EMPTY>
 <!ATTLIST jugador nombre NMTOKENS #REQUIRED>
 <!ATTLIST jugador codigo ID #REQUIRED>
 <!ELEMENT equipo EMPTY>
 <!ATTLIST equipo nombre CDATA #REQUIRED>
 <!ATTLIST equipo jugadores IDREFS #IMPLIED>
]>
<futbol>
 <jugador nombre="Alfredo Di Stéfano" codigo="ads"/>
 <jugador nombre="Edison Arantes do Nascimento" codigo="ean" />
 <jugador nombre="Diego Armando Maradona" codigo="dam" />
 <jugador nombre="Johan Cruyff" codigo="jc" />
 <equipo nombre="Società Sportiva Calcio Napoli" jugadores="dam" />
 <equipo nombre="Futbol Club Barcelona" jugadores="jc  dam" />
</futbol>


7-
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro [
 <!ELEMENT libro EMPTY>
 <!ATTLIST libro autor NMTOKENS #REQUIRED>
]>
<libro autor="Mario Vargas LLosa" />
8-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventores [
 <!ELEMENT inventores (inventor*)>
 <!ELEMENT inventor EMPTY>
 <!ATTLIST inventor invento NMTOKENS #REQUIRED>
 <!ATTLIST inventor nombre NMTOKENS #IMPLIED>
]>
<inventores>
 <inventor nombre="Robert Adler" invento="Mando a distancia" />
 <inventor nombre="Laszlo Josef Biro" invento="Bolígrafo" />
 <inventor nombre="Josephine Garis Cochran" invento="Lavaplatos" />
 <inventor invento="Fuego" />
</inventores>


9-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cosasPorHacer [
 <!ELEMENT cosasPorHacer (cosa*)>
 <!ELEMENT cosa (#PCDATA)>
 <!ATTLIST cosa fecha CDATA #REQUIRED>
 <!ATTLIST cosa fechaLimite CDATA #REQUIRED>
]>
<cosasPorHacer>
 <cosa fecha="20 de febrero de 2011" fechaLimite="1 de marzo de 2011">
 Preparar ejercicios de DTDs</cosa>
 <cosa fecha="21 de febrero de 2011" fechaLimite="5 de marzo de 2011">
 Preparar tema XSLT</cosa>
</cosasPorHacer>


10-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resoluciones [
 <!ELEMENT resoluciones (resolucion*)>
 <!ELEMENT resolucion EMPTY>
 <!ATTLIST resolucion nombre NMTOKENS #REQUIRED>
 <!ATTLIST resolucion alto CDATA #REQUIRED>
 <!ATTLIST resolucion ancho CDATA #REQUIRED>
]>
<resoluciones>
 <resolucion nombre="VGA" alto="480" ancho="640" />
 <resolucion nombre="XGA" alto="1024" ancho="768" />
 <resolucion nombre="HD 1080" alto="1920" ancho="1080" />
</resoluciones>



11-


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albumesMortadelo [
 <!ELEMENT albumesMortadelo (album*)>
 <!ELEMENT album EMPTY>
 <!ATTLIST album nombre CDATA #REQUIRED>
 <!ATTLIST album fecha (1969|1970|1971|1972|1973|1974) #REQUIRED>
]>
<albumesMortadelo>
 <album nombre="El sulfato atómico" fecha="1969"/>
 <album nombre="La caja de diez cerrojos" fecha="1971"/>
 <album nombre="El otro yo del profesor Bacterio" fecha="1973"/>
 <album nombre="Los cacharros majaretas" fecha="1974"/>
</albumesMortadelo>
