=== frango9000/LMSXI_Boletines/b25/6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="libros">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="autor" type="xs:string" maxOccurs="unbounded"/>
              <xs:element name="fecha" type="xs:string"/>
              <xs:element name="isbn">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{3}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="editor" type="xs:string"/>
              <xs:element name="categ">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="ficcion|no ficcion"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="stock" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="revisor" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== frango9000/LMSXI_Boletines/b25/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/local/DANIELCASTELAO/fsancheztemprano/Documentos/LMSXI/b25/6.xsd">
  <libro>
    <titulo>Los hombres que no amaban a las mujeres</titulo>
    <autor>Stieg Larsson</autor>
    <autor/>
    <fecha>2008</fecha>
    <isbn>978-84-233</isbn>
    <editor>Destino</editor>
    <categ>ficcion</categ>
    <stock>Si</stock>
  </libro>
  <libro revisor="Luis Rodrigo">
    <titulo>Java a través de los tiempos</titulo>
    <autor>Jesús Bobadilla</autor>
    <autor>Adela Sancho</autor>
    <fecha>2003</fecha>
    <isbn>978-84-567</isbn>
    <editor>Ra-Ma</editor>
    <categ>no ficcion</categ>
    <stock>No</stock>
  </libro>
</libros>
