       1-Pon un ejemplo de cada caso

	  
a) <elemento>contenido</elemento>
b) <elementovacio />
c) <color interior="negro" exterior="blanco" />
d) <tienda>C &amp A</tienda>
e) <!-- texto comentario -->  




2- El siguiente documento no está bien formado porque contiene errores. Corrige los errores (si para corregir algún error hay que inventarse una etiqueta o atributo, utilice un nombre que tenga relación con la información contenida en el documento).

<?xml version="1.0" encoding="UTF-8"?>
<documento>
         <autor >Pedro García</autor>
         <fecha fecha="30/05/11" />
         <contenido>
         <punto numero="1">XML significa eXtensible Markup Languages</punto>
         </contenido>
</documento>




3- El siguiente documento no está bien formado porque contiene errores. Corrige los errores (si para corregir algún error hay que inventarse una etiqueta o atributo, utilice un nombre que tenga relación con la información contenida en el documento).

<?xml version="1.0" encoding="UTF-8"?>
<personas>
<persona>
<nombre email="pepito.fer@example.org">Pepito Fernández</nombre>
</persona>
<persona>
<nombre>Juanita Pérez</nombre>
<telefonos>
<fijo>3141593</fijo>
</telefonos>
</persona>
</personas>


4- Escribe el DTD que corresponde al siguiente documento  (externa)
   <!ELEMENT formula1 (carrera) >
   <!ELEMENT carrera (nombre, fecha, podium ) >
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT fecha ANY >
   <!ELEMENT dia (#PCDATA)>
   <!ELEMENT mes (#PCDATA)>
   <!ELEMENT año (#PCDATA)>
   <!ELEMENT podium (orden*) >
   <!ELEMENT orden EMPTY >
   
    <!ATTLIST formula1 año CDATA #REQUIRED>
    <!ATTLIST orden n CDATA #REQUIRED
			nombre CDATA #REQUIRED
			escudería CDATA #IMPLIED>
5- Escribe un XML para el DTD siguiente:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
<!ELEMENT agenda (persona)+>
<!ELEMENT persona (nombre, email*, relacion?)>
<!ATTLIST persona id ID #REQUIRED>
<!ATTLIST persona sexo (hombre | mujer) #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT relacion EMPTY>
<!ATTLIST relacion amigo-de IDREFS #IMPLIED enemigo-de IDREFS #IMPLIED>
   ]>

       <agenda>
       <persona id="P001" sexo="hombre">
         <nombre>Francisco Sanchez</nombre>
         <email>a@a.a</email>
         <relacion amigo-de="P001" enemigo-de="P001"/>
         </persona>
       </agenda>

6-  Haz una declaración de espacio de nombres, que asocia el prefijo del espacio de nombres edi con el nombre de espacio de nombres:  http://ecommerce.example.org/schema
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edi:cliente[
<!ELEMENT edi:cliente (edi:numero_ID, edi:nombre, edi:telefono)>
<!ELEMENT edi:numero_ID (#PCDATA)>
<!ELEMENT edi:nombre (#PCDATA)>
<!ELEMENT edi:telefono (#PCDATA)>
<!ATTLIST edi:cliente xmlns:edi CDATA #REQUIRED>
]>

<edi:cliente xmlns:edi="http://ecommerce.example.org/schema: ">
    <edi:numero_ID>1232654</edi:numero_ID>
    <edi:nombre>Jorge Ruiz</edi:nombre>
    <edi:telefono>99999999</edi:telefono>
</edi:cliente>

7- Corrige el documento para que cumpla el DTD.
<?xml version="1.0" encoding="UTF-8"?>
       <!DOCTYPE softwareLibre [
         <!ELEMENT softwareLibre (licencias| aplicaciones)*>
         <!ELEMENT licencias (licencia*)>
         <!ELEMENT licencia EMPTY>
         <!ELEMENT aplicaciones (aplicacion*)>
         <!ELEMENT aplicacion (version*)>
         <!ELEMENT version EMPTY>
         <!ATTLIST licencia nombre ID #REQUIRED>
         <!ATTLIST aplicacion nombre NMTOKEN #REQUIRED>
         <!ATTLIST version nombre NMTOKEN #REQUIRED>
         <!ATTLIST version licencia IDREF #REQUIRED>
         <!ATTLIST version fechaPublicación CDATA #REQUIRED>
       ]>
       <softwareLibre>
         <aplicaciones>
           <aplicacion nombre="Inkscape">
             <version nombre="0.47" licencia="GPLv2" fechaPublicación="17/08/2010" />
             <version nombre="0.48" licencia="GPLv2" fechaPublicación="17/08/2010" />
             <version nombre="0.48.2" licencia="GPLv2" fechaPublicación="14/08/2011" />
           </aplicacion>
           <aplicacion nombre="PostgreSQL">
             <version nombre="9.1.0" licencia="BSD2" fechaPublicación="15/09/2011" />
             <version nombre="9.1.3" licencia="BSD2" fechaPublicación="15/09/2011"/>
           </aplicacion>
         </aplicaciones>
         <licencias>
           <licencia nombre="GPLv2" />
           <licencia nombre="BSD2" />
           <licencia nombre="Apachev2" />
         </licencias>
       </softwareLibre>


8-  Valida el siguiente XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arbol [
         <!ELEMENT arbol (lugares| personas)*>
         <!ELEMENT lugares (lugar*)>
         <!ELEMENT lugar EMPTY>

         <!ELEMENT personas (persona*)>
         <!ELEMENT persona (nombre, padre*,madre*, nacimiento)>
         
         <!ELEMENT nombre (#PCDATA)>
         <!ELEMENT padre (#PCDATA)>
         <!ELEMENT madre (#PCDATA)>
         <!ELEMENT nacimiento EMPTY>
         
         <!ATTLIST lugar nombre CDATA #REQUIRED pais CDATA #REQUIRED>
         <!ATTLIST nacimiento lugar CDATA #REQUIRED año CDATA #IMPLIED mes CDATA #IMPLIED dia CDATA #IMPLIED>
]>

<arbol>
  <lugares>
    <lugar nombre="Valencia" pais="España" />
    <lugar nombre="Gandia" pais="España" />
    <lugar nombre="Marsella" pais="Francia" />
  </lugares>
  <personas>
    <persona>
      <nombre>Ramón Ramírez Villaescusa</nombre>
      <padre>Pedro Ramírez Dupont</padre>
      <nacimiento lugar="Gandia" año="1976" mes="10" dia="3" />
    </persona>
    <persona>
      <nombre>Elena Forte Ramírez</nombre>
      <madre>Juana Ramírez Dupont</madre>
      <nacimiento lugar="Valencia" año="1974" mes="05" dia="31" />
    </persona>
    <persona>
      <nombre>Pedro Ramírez Dupont</nombre>
      <padre>Juan Ramírez Amigo</padre>
      <madre>Jeanne Dupont</madre>
      <nacimiento lugar="Gandia" año="1942" mes="07" dia="14" />
    </persona>
    <persona>
      <nombre>Juana Ramírez Dupont</nombre>
      <padre>Juan Ramírez Amigo</padre>
      <madre>Jeanne Dupont</madre>
      <nacimiento lugar="Valencia" año="1945" mes="02" dia="20" />
    </persona>
    <persona>
      <nombre>Juan Ramírez Amigo</nombre>
      <nacimiento lugar="Gandia" año="1918" mes="07" dia="19" />
    </persona>
    <persona>
      <nombre>Jeanne Dupont</nombre>
      <nacimiento lugar="Marsella" />
    </persona>
  </personas>
</arbol>
	9-    Forma un documento XML válido en el que recojas diferentes tipos de lenguajes de programación,   creando un namespace para los compilados y otro para los interpretados.
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lenguajes [
 <!ELEMENT lenguajes (lenguaje*)>
 <!ELEMENT lenguaje (nombre, creador, fecha, (compilado | interpretado))>
 <!ELEMENT compilado EMPTY>
 <!ELEMENT interpretado EMPTY>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT creador (#PCDATA)>
 <!ELEMENT fecha (#PCDATA)>
 
<!ATTLIST compilado xmlns:android CDATA #REQUIRED>
<!ATTLIST interpretado xmlns:android CDATA #REQUIRED>
]>
<lenguajes>
  <lenguaje>
    <nombre>C</nombre>
    <creador>Dennis Ritchie</creador>
    <fecha>1973</fecha>
    <compilado xmlns:android="http://schemas.android.com/apk/res/android" />
  </lenguaje>
  <lenguaje>
    <nombre>Python</nombre>
    <creador>Guido van Rossum</creador>
    <fecha>1991</fecha>
    <interpretado xmlns:android="http://schemas.android.com/apk/res/android" />
  </lenguaje>
  <lenguaje>
    <nombre>PHP</nombre>
    <creador>Rasmus Lerdorf</creador>
    <fecha>1995</fecha>
    <interpretado xmlns:android="http://schemas.android.com/apk/res/android" />
  </lenguaje>
  <lenguaje>
    <nombre>XSLT</nombre>
    <creador>James Clark</creador>
    <fecha>1998</fecha>
    <interpretado xmlns:android="http://schemas.android.com/apk/res/android" />
  </lenguaje>
</lenguajes>


<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE tebeos[
<!ELEMENT tebeos (autor, UltimaModificacion, personajes, autores, albumes)>

<!ELEMENT autor (#PCDATA)>
<!ELEMENT UltimaModificacion (#PCDATA)>
<!ELEMENT personajes (personaje*)>
<!ELEMENT personaje (#PCDATA)>
<!ELEMENT autores (dibujantes, guionistas)>
<!ELEMENT albumes (album* )>
<!ELEMENT album (titulo, personajes, autores, fechaPublicacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fechaPublicacion (#PCDATA)>

<!ELEMENT dibujantes (dibujante*)>
<!ELEMENT guionistas (guionista*)>

<!ELEMENT dibujante (nombre?, apodo?, nacimientoFecha?, nacimientoPais?,fallecimientoFecha?)>
<!ELEMENT guionista (nombre?, nacimientoFecha?, nacimientoPais?,fallecimientoFecha?)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apodo (#PCDATA)>
<!ELEMENT nacimientoFecha (#PCDATA)>
<!ELEMENT nacimientoPais (#PCDATA)>
<!ELEMENT fallecimientoFecha (#PCDATA)>

<!ATTLIST personaje id ID #IMPLIED>
<!ATTLIST personaje especie CDATA #IMPLIED>

<!ATTLIST dibujante id ID #IMPLIED>
<!ATTLIST guionista id ID #IMPLIED>
<!ATTLIST album id ID #IMPLIED>


]>


<tebeos>
  <autor>Bernardo Garcia  Marcial </autor>
  <UltimaModificacion>20120601</UltimaModificacion>
  <personajes>
    <personaje id="P001" especie="humano">Astérix</personaje>
    <personaje id="P002" especie="animal">Idéfix</personaje>
    <personaje id="P003" especie="humano">Lucky Luke</personaje>
    <personaje id="P004" especie="animal">Jolly Jumper</personaje>
    <personaje id="P005" especie="humano">Averrell Dalton</personaje>
    <personaje id="P006" especie="humano">Cayo coyuntural</personaje>
  </personajes>
  <autores>
    <dibujantes>
      <dibujante id="D001">
        <nombre>Albert Uderzo</nombre>
        <nacimientoFecha>1927</nacimientoFecha>
        <nacimientoPais>Francia</nacimientoPais>
      </dibujante>
      <dibujante id="D002">
        <nombre>Maurice de Bévère</nombre>
        <apodo>Morris</apodo>
        <nacimientoFecha>1923</nacimientoFecha>
        <nacimientoPais>Bélgica</nacimientoPais>
        <fallecimientoFecha>2001</fallecimientoFecha>
      </dibujante>
    </dibujantes>
    <guionistas>
      <guionista id="G001">
        <nombre>René Goscinny</nombre>
        <nacimientoFecha>1926</nacimientoFecha>
        <nacimientoPais>Francia</nacimientoPais>
        <fallecimientoFecha>1977</fallecimientoFecha>
      </guionista>
    </guionistas>
  </autores>
  <albumes>
    <album id="A001">
      <titulo>Astérix, el galo</titulo>
      <personajes>
        <personaje>P001</personaje>
        <personaje>P002</personaje>
      </personajes>
      <autores>
        <dibujante>D001</dibujante>
        <guionista>G001</guionista>
      </autores>
      <fechaPublicacion>1961</fechaPublicacion>
    </album>
    <album id="A002">
      <titulo>Indulto para los Dalton</titulo>
      <personajes>
        <personaje>P003</personaje>
        <personaje>P004</personaje>
        <personaje>P005</personaje>
      </personajes>
      <autores>
        <dibujante>D002</dibujante>
        <guionista>G001</guionista>
      </autores>
      <fechaPublicacion>1965</fechaPublicacion>
    </album>
    <album id="A001">
      <titulo>Obélix y compañia</titulo>
      <personajes>
        <personaje>P001</personaje>
        <personaje>P002</personaje>
        <personaje>P006</personaje>
      </personajes>
      <autores>
        <dibujante>D001</dibujante>
        <guionista>G001</guionista>
      </autores>
      <fechaPublicacion>1976</fechaPublicacion>
    </album>
    
  </albumes>
</tebeos>